### ISSUE TITLE
zookeeper版本

### ISSUE THREAD

**Issue by NotEdibleSalt** [luojian220/elasticjob-lite-springboot-demo#1]
大神，你用的zookeeper是那个版本的？我用3.6、3.6.1、3.6.2都连不上。一直报org.apache.zookeeper.KeeperException$OperationTimeoutException: KeeperErrorCode = OperationTimeout异常

**Comment by lsiuf** [comment]
> 大神，你用的zookeeper是那个版本的？我用3.6、3.6.1、3.6.2都连不上。一直报org.apache.zookeeper.KeeperException $ OperationTimeoutException：KeeperErrorCode = OperationTimeout异常

我也出现了这个问题，我是使用maxRetries参数增加zk重连次数解决的，你可以试下
`elasticjob.reg-center.max-retries: 10`

**Comment by luojian220** [comment]
zookeeper 3.6.2  是可以的。

**Comment by NotEdibleSalt** [comment]
> 
> 
> > 大神，你用的zookeeper是那个版本的？我用3.6、3.6.1、3.6.2都连不上。一直报org.apache.zookeeper.KeeperException $ OperationTimeoutException：KeeperErrorCode = OperationTimeout异常
> 
> 我也出现了这个问题，我是使用maxRetries参数增加zk重连次数解决的，你可以试下
> `elasticjob.reg-center.max-retries: 10`

感谢大神，可以了。

**Comment by NotEdibleSalt** [comment]
> 
> 
> zookeeper 3.6.2 是可以的。

嗯嗯，zookeeper 3.6.2 可以
